export class Avaliacao {
  constructor(
    public aluno: string,
    public dataavaliacao: Date,
    public peso: string,
    public altura: string,
    public imc: string,
    public rcq: string,
    public pGordura: string,
    public pRecomendado: string,
    public gorduraAtual: string,
    public gorduraExcedente: string,
    public massaMagra: string,
    public carenciaMassa: string,
    public pesoEstimado: string,
    public torax: string,
    public cintura: string,
    public abdomem: string,
    public quadril: string,
    public coxaDireita: string,
    public coxaEsquerda: string,
    public panturrilhaDireita: string,
    public panturrilhaEsquerda: string,
    public bracoDireito: string,
    public bracoEsquerdo: string,
    public antibracoDireito: string,
    public antibracoEsquerdo: string,
  ) { }
}
